### ISSUE TITLE
Title gets sometimes stuck when switching to an empty virtual desktop

### ISSUE THREAD

**Issue by wsdfhjxc** [psifidotos/applet-window-title#86] opened 2020-01-21 16:52 UTC
This isn't always reproducible, but I can see it occurring quite often. For example, if I have a Kate's window focused on one virtual desktop, and then I switch to an empty virtual desktop, the title displayed by the applet might still contain Kate's window title. However, this happens only if the applet is placed in a Latte panel. If the applet is placed in a Plasma panel, it seems to be working correctly.

I was also able to reproduce this behavior couple of times on a fresh Kubuntu 19.10 install with backports and following component versions: Plasma 5.17.5, Frameworks 5.66, Latte Dock 0.9.7.

**Comment by psifidotos** [comment] 2020-01-21 18:27
I cant reproduce this in my system...

are you using the applet master version?

**Comment by wsdfhjxc** [comment] 2020-01-21 21:05
Yes, it's the git master version.

Here's a preview of the issue recorded in a VM.

The top panel is a Latte panel and the bottom panel is a Plasma panel. 

![preview](https://user-images.githubusercontent.com/20323160/72841927-ad184a80-3c97-11ea-81a9-92847cbeb7d3.gif)

You can see how Firefox's window title kindly disappears in the Plasma panel, but gets stuck in the Latte panel after switching to an empty virtual desktop. Both applets are configured identically. It's not always reproducible, so it must be some really strange case, when the applet misses signals or something.

**Comment by psifidotos** [comment] 2020-01-21 21:17
the Latte codepath and the Plasma codepath is different... but how that is tracked down I dont know yet...

Show me a screenshot of your applet settings

**Comment by wsdfhjxc** [comment] 2020-01-21 21:42
Here you go.

![1](https://user-images.githubusercontent.com/20323160/72844604-2c5c4d00-3c9d-11ea-84de-ad53c0782d28.png)

![2](https://user-images.githubusercontent.com/20323160/72844605-2cf4e380-3c9d-11ea-8b22-94a93bb34670.png)

Changing applet options (such as "Filters" or "Placeholder"), as well as Latte options (such as "Track From" or "Drag and maximise/restore active window"), seem not to impact the issue, as it's still happening despite altering these options. Maybe there is something that needs to be fixed in Latte?

**Comment by psifidotos** [comment] 2020-01-21 22:14
If you enable for applet settings Behavior -> Show only window information from current screen

is the bug still present?

**Comment by wsdfhjxc** [comment] 2020-01-21 22:44
Yes, the bug is still present. And I've also tried Latte 0.9.85 version, but I can still reproduce the issue. That might require further investigation, maybe something in Latte's window tracker component?

Anyway, thank you for your time!

**Comment by psifidotos** [comment] 2020-01-21 22:57
Probably but in order to identify what breaks I would need a standard way to reproduce this in my system

**Comment by psifidotos** [comment] 2020-05-24 00:07
Is this still valid with latest Latte git version?

**Comment by wsdfhjxc** [comment] 2020-08-23 16:46
Yes, the bug is still present.

**Comment by psifidotos** [comment] 2021-07-18 07:14
@wsdfhjxc can you please test with latest Latte git version. Big chance is that is now fixed.

**Closed** 2021-07-18 07:15 UTC
